model_type: gru_text
known_model_data_types:
  naive
  gru_text
  gru_text_subgoal
data_folder_path: /Volumes/Extreme SSD/teach-dataset
model_checkpoints_pre_path: ./model_checkpoints_out/
model_load_name: epoch=0-step=44.ckpt
naive:
  wv2_path:  /Volumes/Extreme SSD/GoogleNews-vectors-negative300.bin.gz
  x_text_pad_length: 100
  x_prev_action_pad_length: 100
  auto_lr_find: True
gru_text:
  input_lang_path: /Volumes/Extreme SSD/teach_input_lang.pickle
  output_lang_path: /Volumes/Extreme SSD/teach_output_lang.pickle
  save_input_lang_path: /Volumes/Extreme SSD/new_teach_input_lang.pickle
  save_output_lang_path: /Volumes/Extreme SSD/new_teach_input_lang.pickle
  encoder_hidden_size: 256
  decoder_hidden_size: 256
  teacher_forcing: True
  decoder_dropout_p: 0.5
  auto_lr_find: False
  max_length: 1000
  max_output_length: 1000
  output_length_delta: 10
  use_single_optimizer: False
gru_text_subgoal:
  input_lang_path: /Volumes/Extreme SSD/teach_subgoal_input_lang.pickle
  output_lang_path: /Volumes/Extreme SSD/teach_subgoal_output_lang.pickle
  save_input_lang_path: /Volumes/Extreme SSD/new_teach_input_lang.pickle
  save_output_lang_path: /Volumes/Extreme SSD/new_teach_input_lang.pickle
  encoder_hidden_size: 256
  decoder_hidden_size: 256
  teacher_forcing: True
  decoder_dropout_p: 0.5
  auto_lr_find: False
  max_length: 1000
  max_output_length: 1000
  output_length_delta: 10
  use_subgoal_history: True
  use_subgoal_future: True
  use_commander_language: True
  use_follower_language: True
  use_single_optimizer: False
trainer:
  checkpoints_save_top_k: 3
  acc_device: gpu
  devices: '0'
  fallback_devices: 1
  auto_lr_find: True
  track_grad_norm: 2
  gradient_clip_val: 0.5
  gradient_clip_algorithm: value
  max_epochs: 100
  num_sanity_val_steps: 1
  detect_anomaly: False
  fast_dev_run: False
  lr: 0.0001
  check_val_every_n_epoch: 10
  val_check_interval: 1
datamodule:
  num_workers: 8
  batch_size: 128
  validation_batch_size: 1
  use_small_dataset: False
  save_data_preprocessing: False
  fail_if_cannot_load: False
wandb:
  project: toast
  offline: False
  group_name: gru_text_test
  log_model: False
  entity: 'nlp4robots-toast'