model_type: gru_text
data_folder_path: /home/sethsclass/teach-dataset
model_checkpoints_path: ./model_checkpoints_out/
model_load_name: epoch=0-step=44.ckpt
naive:
  wv2_path:  /home/sethsclass/GoogleNews-vectors-negative300.bin.gz
  x_text_pad_length: 100
  x_prev_action_pad_length: 100
  auto_lr_find: True
gru_text:
  input_lang_path: /home/sethsclass/teach_input_lang.pickle
  output_lang_path: /home/sethsclass/teach_output_lang.pickle
  encoder_hidden_size: 256
  decoder_hidden_size: 256
  teacher_forcing: True
  decoder_dropout_p: 0.5
  auto_lr_find: False
  max_length: 1000
trainer:
  checkpoints_save_top_k: 3
  acc_device: gpu
  devices: '0'
  auto_lr_find: True
  track_grad_norm: 2
  gradient_clip_val: 0.5
  gradient_clip_algorithm: value
  max_epochs: 100
  num_sanity_val_steps: 3
  detect_anomaly: False
  fast_dev_run: False
lr: 0.0001
batch_size: 128
use_small_dataset: False
